### ISSUE TITLE
"You appear to have already installed WordPress."

### ISSUE THREAD

**Issue by JulianKingman** [tutumcloud/wordpress-stackable#31]
I'm trying to create a new installation of wordpress, stackable, and I'm getting this error:
````
You appear to have already installed WordPress. To reinstall please clear your old database tables first.
````
I have one install working on another domain, so I created a new, similar stack, and all was well, until I decided to change some more things and redeploy. Now it's giving me the above error, even if I terminate the whole stack and redeploy. Here's my whole stackfile:

````
drhWordpress-storage:
  image: 'tutum/wordpress-stackable:latest'
  volumes:
    - /app/wp-content/plugins
    - /app/wp-content/themes
    - /app/wp-content/uploads
    - /var/lib/mysql
drhDb:
  image: 'tutum/mysql:5.5'
  environment:
    - MYSQL_PASS=examplepassword
  volumes_from:
    - drhWordpress-storage
drhPhpMyAdmin:
  image: 'corbinu/docker-phpmyadmin:latest'
  environment:
    - MYSQL_USERNAME=root
    - MYSQL_ROOT_PASSWORD=examplepassword
  links:
    - 'drhDb:mysql'
  ports:
    - '4105:80'
drhSftp:
  image: 'luzifer/sftp-share:latest'
  environment:
    - PASS=examplepassword
    - USER=julian
  ports:
    - '2025:22'
  volumes_from:
    - drhWordpress-storage
drhWordpress:
  image: 'tutum/wordpress-stackable:latest'
  environment:
    - VIRTUAL_HOST=example.com
    - DB_PASS=examplepassword
  links:
    - drhDb
  volumes_from:
    - drhWordpress-storage
````
